//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Id { get; set; }
        public string BlogName { get; set; }
        public string Photo { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> TimeCreate { get; set; }
        public Nullable<int> EmpployeeCreate { get; set; }
        public Nullable<int> Tag { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
