//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    
    public partial class GetCategoryWithGender_Result1
    {
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public string ParentId { get; set; }
        public string Type { get; set; }
    }
}
